version: '3'
services:
  discovery_33:
    container_name: discovery-server #== services.discovery.container_name
    build:
      ./discovery
    ports:
      - 8761:8761
    networks:
    - webnet
  config:
    container_name: config
    build:
      ./config
    volumes:
    - ./config-data:/var/config-data
    environment:
    - JAVA_OPTS=
      -DEUREKA_SERVER=http://discovery:8761/eureka
      -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
    - discovery_33
    ports:
      - 8888:8888
    networks:
    - webnet
  school-service:
    build:
      ./school-server
    environment:
    - JAVA_OPTS=
      -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
    - discovery_33
    - config
    ports:
     - 8081:8081
    networks:
    - webnet
  school-ui:
    build:
      ./school-ui
    environment:
    - JAVA_OPTS=
      -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
    - discovery_33
    - config
    ports:
      - 8080:8080
    networks:
    - webnet
#  mysql_db:
#    image: mysql:latest
#    networks:
#    - webnet
#    ports:
#      - 3306:3306

networks:
  webnet: